export type ISettings = {
    title: string;
    favicon?: string;
    favicon_key?: string;
    logo?: string;
    logo_key?: string;
    phone?: string;
    email?: string;
    address?: string;
    facebook_link?: string;
    instagram_link?: string;
    twitter_link?: string;
    youtube_link?: string;
    whatsapp_link?: string;
    welcome_message?: string;
    about?: string;
    return_policy?: string;
    privacy_policy?: string;
    refund_policy?: string;
    cancellation_policy?: string;
    terms?: string;
    shipping_info?: string;
  };